### ISSUE TITLE
Beta checklist

### ISSUE THREAD

**Issue by danieljharvey** [danieljharvey/horses#171]
It would be nice to share this for people to use, even if none really do. For that to be nice, we need the following:

- [x] #168 - stop one person crashing everything
- [x] #191 - a basic standard library when starting a new project so it’s not a case of reinventing the wheel each time
- [x] code highlighting
- [x] JS zip downloads
- [x] a basic test runtime (maybe the repo one? Or just console.log for now?)
- [ ] about page / basic docs (i guess the code samples will offer some explanation)
- [x] array type
- [ ] JSON parser?

**Comment by danieljharvey** [comment]
Totally went off on one making new features, abandoning this.
