### ISSUE TITLE
Modules in UI

### ISSUE THREAD

**Issue by danieljharvey** [danieljharvey/horses#722]
To make a minimal version of this work, we need the following:

- [x] a new scratch screen that evaluates modules (#721 )
- [x] display modules at the bottom of the screen as well as project bindings / types (#724 )
- [x] view modules endpoints (#728)
- [ ] edit modules endpoints
- [x] be able to compile a module to Typescript

Probably lots more.

**Comment by danieljharvey** [comment]
Killed the UI, soz
